### ISSUE TITLE
Crear endpoint para obtener el mapa de calor

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-back#1]
Desarrollar el endpoint GET /api/mapa-calor que devuelva datos en tiempo real sobre la congestión turística en diferentes zonas de la ciudad. Asegurarse de que el endpoint se conecte con las APIs de HERE Maps y OpenStreetMap para obtener los datos.

**Comment by DavidCosta92** [comment]
El endpoint de mapa de calor ya estaria funcional, listo para empezar a realizar integracion. El unico detalle es que se esta alimientando solo de informacion de trafico, estamos en proceso de poder añadir la informacion que se recibe de google places. De todos modos, la respuesta al frontend no deberia cambiar de formato, por lo que se puede empezar a conectar.
