### ISSUE TITLE
Implementar cifrado de datos sensibles de usuarios

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-back#11]
Asegurarse de que los datos sensibles de los usuarios, como las preferencias y el historial de navegación, estén correctamente cifrados al almacenarse en la base de datos. Utilizar algoritmos de cifrado seguros.

**Comment by pbl99** [comment]
Se ha implementado un cifrado con AES para que en la base de datos esten guardadas tanto las preferencias como los lugares favoritos
