### ISSUE TITLE
Escribir pruebas unitarias para el servicio de recomendaciones

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-back#13]
Desarrollar pruebas unitarias para el 'RecomendacionesService' asegurando que las recomendaciones de destinos menos concurridos sean precisas y se ajusten a los datos de congestión y ubicación en tiempo real.

**Comment by pbl99** [comment]
Se escribe el test DestineRecommendationServiceImplTest que maneja que se devuelvan bien los resultados de las recomendaciones , la api junto a otro servicio que creamos ya maneja directamente que se pasen los destinos menos concurridos y en tiempo real
