### ISSUE TITLE
Mejorar la seguridad de las recomendaciones de destinos

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-back#16]
Asegurarse de que las recomendaciones de destinos en el 'RecomendacionesService' estén protegidas contra ataques de inyección de datos y que solo se muestren destinos verificados. Implementar controles de seguridad en las consultas.

**Comment by pbl99** [comment]
Las recomendaciones se hacen desde la api externa , a través de las preferencias del usuario , las cuales estan encriptadas en la base de datos , los destinos estan verificados y son exclusivos de los que la api externa contiene
