### ISSUE TITLE
Crear endpoint para recomendaciones de destinos alternativos

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-back#2]
Desarrollar el endpoint GET /api/destinos/recomendaciones que devuelva recomendaciones de destinos menos concurridos, basados en la congestión actual y la ubicación del usuario. Asegurarse de que los datos sean precisos y se actualicen en tiempo real.

**Comment by DavidCosta92** [comment]
Esta funcion esta en el enpoint destines/,  donde pasando la ubicacion del usuario se obtiene los destinos con su congestion actual.. Queda pendiente ordenar los destinos por congestion y ubicacion del usuario directamente desde la api externa
