### ISSUE TITLE
Crear endpoint para filtrar destinos turísticos

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-back#3]
Desarrollar el endpoint GET /api/destinos/filtrar que permita a los usuarios aplicar filtros personalizados (tipo de actividad, distancia, nivel de saturación) y devuelva una lista de destinos ajustada a sus preferencias.

**Comment by DavidCosta92** [comment]
Endpoint => /api/v1/destines/ => Implementacion en proceso, definiendo detalles de respuesta, pero en lineas generales esta avanzado el desarrollo

**Comment by pbl99** [comment]
Se implementa y devuelve listas pueden ser variables en numero de destinos , de radio , de preferencia , de latitud y longitud de máxima afluencia , y devuelve datos como nombre destino , calle , rating de puntuacion de usuarios , horario de apertura y cierra etc..
