### ISSUE TITLE
Desarrollar servicio de integración con HERE Maps

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-back#6]
Crear el 'MapaCalorService' que se conecte con las APIs de HERE Maps para obtener datos de congestión en tiempo real. Asegurarse de que los datos se procesen adecuadamente antes de enviarlos al frontend.

**Comment by DavidCosta92** [comment]
Integracion con here maps, para mapa de calor esta lista! Solo queda pendiente pulir la informacion requerida sobre los detalles de los destinos, que debera ser discutido con frontend.
