### ISSUE TITLE
Optimizar las consultas de destinos en el backend

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-back#7]
Revisar y optimizar las consultas de base de datos relacionadas con la obtención de destinos turísticos y sus recomendaciones. Asegurarse de que las consultas sean eficientes y que el tiempo de respuesta sea rápido.

**Comment by pbl99** [comment]
Se ha implementado redis para la consulta de getfilteredvenus que trae hasta 100 o mas destinos por latitud y longitud del usuario radio de distancia variable igual que nivel de afluencia
