### ISSUE TITLE
Implementar sistema de cache para mejorar el rendimiento

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-altour-back#9]
Implementar un sistema de cache en el backend para almacenar temporalmente los datos de congestión y recomendaciones de destinos. Esto mejorará el tiempo de respuesta y reducirá la carga en las APIs externas.

**Comment by pbl99** [comment]
Se implementa un sistema de cache con redis para los datos de destinos con sus afluencias actuales y uno para las recomendaciones como es variable y puede variar rápido se implementa por un tiempo de 10 minutos , además se añade una pequeña variabilidad en la latitud y longitud en ambos para que si la latitud y longitud varia ligeramente aun estando en el mismo sitio el cache siga persistiendo .
